services:
  - type: web
    name: ca-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://zintech04.com:5000/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
